name: youreit1
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.11.0
  - aiohttp=3.7.2
  - astor=0.8.1
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - boto=2.49.0
  - boto3=1.9.66
  - botocore=1.12.67
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - cachetools=4.1.1
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - cryptography=3.1.1
  - cycler=0.10.0
  - docutils=0.16
  - freetype=2.10.4
  - gast=0.2.2
  - gensim=3.8.0
  - google-api-core=1.22.2
  - google-auth=1.23.0
  - google-cloud-core=1.4.3
  - google-cloud-storage=1.32.0
  - google-crc32c=1.0.0
  - google-pasta=0.2.0
  - google-resumable-media=1.1.0
  - googleapis-common-protos=1.52.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=2.10
  - importlib-metadata=2.0.0
  - intel-openmp=2019.4
  - jmespath=0.10.0
  - joblib=0.17.0
  - jpeg=9b
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.0
  - kiwisolver=1.3.0
  - lcms2=2.11
  - libcrc32c=1.1.1
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libtiff=4.1.0
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - markdown=3.3.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - multidict=4.7.6
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - opt_einsum=3.1.0
  - pandas=1.1.3
  - pillow=8.0.1
  - pip=20.2.4
  - protobuf=3.13.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.24.0
  - rsa=4.6
  - s3transfer=0.1.13
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - setuptools=50.3.0
  - six=1.15.0
  - smart_open=3.0.0
  - sqlite=3.33.0
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.24.3
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - appnope==0.1.0
    - backcall==0.2.0
    - click==7.1.2
    - decorator==4.4.2
    - ipykernel==5.3.4
    - ipyplot==1.1.0
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.8
    - ptyprocess==0.6.0
    - pygments==2.7.2
    - pyzmq==19.0.2
    - regex==2020.10.28
    - shortuuid==1.0.1
    - tqdm==4.51.0
    - traitlets==5.0.5
    - wcwidth==0.2.5
